name: vy_analyzer_utils
description: Simple utility for running an ast visitor on a dart project sources
version: 0.1.3
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  glob: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
