name: vy_analyzer_utils
description: Simple utility for running an ast visitor on a dart project sources
version: 0.1.3
# homepage: https://www.example.com
author: giorgio <giorgiofran@gmail.com>

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  glob: ^1.2.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
