name: vy_analyzer_utils
version: 0.1.2
description: Simple utility for running an ast visitor on a dart project sources

dependencies:
  glob: 1.2.0

dev_dependencies:
  pedantic: 1.8.0
  test: ^1.6.0

environment:
  sdk: ">=2.5.0 <3.0.0"
